#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#logging:
#  level:
#    org:
#      springframework:
#        context: DEBUG
#        web: DEBUG

spring:
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
